title = "Just a Theory"
baseURL = "https://justatheory.com/"
languageCode = "en-us"
copyright = "© David E. Wheeler. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = "justatheory"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PreserveTaxonomyNames = true
# rssLimit = 16
Paginate = 16
PaginatePath = "p"
footnoteReturnLinkContents = "↩"
enableRobotsTXT = true
disableKinds = ["section"]

[author]
    name = "David E. Wheeler"

[params]
  description = "Irregular fine blogging since 2002."
  author = "David E. Wheeler"
  bug = "❖"
  twitter = "theory"
  github = "theory"
  listTypes = ["post"]

[permalinks]
  post = "/:year/:month/:slug/"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[taxonomies]
    tag = "tags"