title = "KTamas' blog"
baseURL = "https://ktamas.github.io/"
languageCode = "en-us"
copyright = "© Tamas Kadar, 2009-2019. All Rights Reserved."
theme = "justatheory"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PreserveTaxonomyNames = true
Paginate = 10
PaginatePath = "p"
footnoteReturnLinkContents = "↩"
enableRobotsTXT = true
disableKinds = ["section"]
disqusShortname = "ktamas"

[author]
    name = "KTamas"
    url = "https://ktamas.github.io/"

[params]
  description = "Bringing you irregular content since 2009. By KTamas."
  tagline = "Remember kids, if Internet Explorer is brave enough to ask to be your default browser, you're brave enough to ask that girl out."
  author = "KTamas"
  bug = ""
  twitter = "ktamas"
  github = "ktamas"
  postTypes = ["post"]
  feedLimit = 32
  recentTagYears = 3
  icon = "/icon-512x512.png"
  favicon = "/icon-64x64.png"

[permalinks]
  post  = "/:year/:month/:slug/"
  photo = "/:year/:month/:slug/"

[mediaTypes]
[mediaTypes."application/atom"]
  suffixes = ["xml"]
[mediaTypes."text/plain"]
  suffixes = ["text"]

[outputFormats]
[outputFormats.atom]
  mediatype = "application/atom"
  baseName = "feed"
[outputFormats.json]
  mediatype = "application/json"
  baseName = "feed"
  isPlainText = true
[outputFormats.text]
  mediatype = "text/plain"
  baseName = "copy"
  isPlainText = true

[outputs]
  home = ["html", "json", "atom"]
  section = ["html", "json", "atom"]
  taxonomy = ["html", "json", "atom"]
  taxonomyTerm = ["html", "json", "atom"]
  page = ["html", "text"]

[taxonomies]
    tag = "tags"
