title = "Just a Theory"
baseURL = "https://justatheory.com/"
languageCode = "en-us"
theme = "justatheory"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PreserveTaxonomyNames = true
Paginate = 1
PaginatePath = "p"

[params]
  favicon = ""
  description = "Theory waxes practical."
  author = "David E. Wheeler"
  bug = "❖"
  twitter = "theory"
  github = "theory"

[permalinks]
  posts = "/:year/:month/:slug/"
