title = "Just a Theory"
baseURL = "https://justatheory.com/"
languageCode = "en-us"
copyright = "© David E. Wheeler. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
theme = "justatheory"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
PreserveTaxonomyNames = true
Paginate = 16
PaginatePath = "p"
footnoteReturnLinkContents = "↩"


[author]
    name = "David E. Wheeler"

[params]
  favicon = ""
  description = "Theory waxes practical."
  author = "David E. Wheeler"
  bug = "❖"
  twitter = "theory"
  github = "theory"

[permalinks]
  posts = "/:year/:month/:slug/"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
